version: "3.9"

services:
  frontend:
    build: ./frontend-vite
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-vite:/app
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/event_db

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: event_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
